"use strict";var K=Object.create;var S=Object.defineProperty;var L=Object.getOwnPropertyDescriptor;var E=Object.getOwnPropertyNames;var U=Object.getPrototypeOf,$=Object.prototype.hasOwnProperty;var M=(t,r)=>()=>(r||t((r={exports:{}}).exports,r),r.exports),q=(t,r)=>{for(var n in r)S(t,n,{get:r[n],enumerable:!0})},F=(t,r,n,a)=>{if(r&&typeof r=="object"||typeof r=="function")for(let i of E(r))!$.call(t,i)&&i!==n&&S(t,i,{get:()=>r[i],enumerable:!(a=L(r,i))||a.enumerable});return t};var B=(t,r,n)=>(n=t!=null?K(U(t)):{},F(r||!t||!t.__esModule?S(n,"default",{value:t,enumerable:!0}):n,t)),V=t=>F(S({},"__esModule",{value:!0}),t);var T=M(u=>{"use strict";var O=u&&u.__assign||function(){return O=Object.assign||function(t){for(var r,n=1,a=arguments.length;n<a;n++){r=arguments[n];for(var i in r)Object.prototype.hasOwnProperty.call(r,i)&&(t[i]=r[i])}return t},O.apply(this,arguments)},D=u&&u.__importStar||function(t){if(t&&t.__esModule)return t;var r={};if(t!=null)for(var n in t)Object.hasOwnProperty.call(t,n)&&(r[n]=t[n]);return r.default=t,r};Object.defineProperty(u,"__esModule",{value:!0});var W=D(require("child_process"));function J(t){return Array.isArray(t)&&Object.prototype.hasOwnProperty.call(t,"raw")}function X(t,r){for(var n="",a=t.length,i=0;i<a;i++){var s=i<a-1?r[i]:"";n+=t[i]+s}return n.trim()}function d(t,r,n){return n===void 0&&(n={}),process.platform!=="darwin"?Promise.reject(new Error("osascript-tag requires macOS")):new Promise(function(a,i){var s=n.argv||[],y=[],v=X(t,r),j="AppleScript";n.language==="JavaScript"&&(j=n.language,v="(function(...argv){"+v+"})("+s.map(function(c){return JSON.stringify(c)})+")"),n.parse&&(y=["-s","s"]),typeof n.flags=="string"&&(y=["-s",n.flags]);var m=W.spawn("osascript",["-l",j].concat(y,["-e",v])),w="";m.stderr.on("data",function(c){w+=c.toString()});var A="";m.stdout.on("data",function(c){A+=c.toString()}),m.on("close",function(){if(w)i(w);else{var c=A;if(n.parse)try{c=JSON.parse(A)}catch(N){i(N)}a(c)}}),m.on("error",function(c){i(c)})})}function P(t){for(var r=[],n=1;n<arguments.length;n++)r[n-1]=arguments[n];return J(t)?d(t,r,{}):function(a){for(var i=[],s=1;s<arguments.length;s++)i[s-1]=arguments[s];return d(a,i,t)}}function b(t){for(var r=[],n=1;n<arguments.length;n++)r[n-1]=arguments[n];return J(t)?d(t,r,{language:"JavaScript"}):function(a){for(var i=[],s=1;s<arguments.length;s++)i[s-1]=arguments[s];return d(a,i,O({language:"JavaScript"},t))}}P.jxa=b;u.jxa=b;u.default=P});var Q={};q(Q,{default:()=>C});module.exports=V(Q);var e=require("@raycast/api");var p=require("@raycast/api"),I=B(T()),k=async(t,r)=>{try{return await I.default.jxa({parse:!0,argv:r})`${t}`}catch(n){if(typeof n=="string"){let a=n.replace("execution error: Error: ","");a.match(/Application can't be found/)?(0,p.showToast)({style:p.Toast.Style.Failure,title:"Application not found",message:"Things must be running"}):(0,p.showToast)({style:p.Toast.Style.Failure,title:"Something went wrong",message:a})}}},R=()=>k(`
		const okjson = Application('net.shinystone.OKJSON');
		return okjson.scripts().map(val => {
			return {
				id: val.id(),
				name: val.name(),
				icon: val.icon(),
				description: val.scriptdescription(),
				path: val.path(),
			}
		})
	`),h=(t,r)=>r?k(`
		const okjson = Application('net.shinystone.OKJSON');
    const input = argv[0]
		okjson.runScript("${t}", { with: input })
	`,[r]):k(`
		const okjson = Application('net.shinystone.OKJSON');
		okjson.runScript("${t}")
	`);var f=require("react");var l=require("@raycast/api");async function z(){return(await(0,l.getApplications)()).some(({bundleId:n})=>n==="net.shinystone.OKJSON")}async function x(){return await z()?Promise.resolve(!0):(await(0,l.confirmAlert)({title:"OK JSON is not installed.",message:"Do you want to install it right now?",primaryAction:{title:"Install",onAction:async()=>{(0,l.open)("https://apps.apple.com/app/ok-json-offline-private/id1576121509?mt=12"),await(0,l.popToRoot)({clearSearchBar:!1})}},dismissAction:{title:"Cancel",onAction:async()=>{await(0,l.popToRoot)({clearSearchBar:!1})}}}),Promise.resolve(!1))}var o=require("react/jsx-runtime");async function g(){await(0,e.closeMainWindow)({clearRootSearch:!0}),(0,e.popToRoot)()}function G(t){let{script:r}=t;return(0,o.jsx)(e.Form,{actions:(0,o.jsx)(e.ActionPanel,{children:(0,o.jsx)(e.Action.SubmitForm,{onSubmit:async n=>{let a=n.input;await h(r.id,a),await g()}})}),children:(0,o.jsx)(e.Form.TextArea,{id:"input",title:"Input",placeholder:"Input you want to pass to the script"})})}function H(t){let{script:r}=t;return(0,o.jsx)(e.List.Item,{actions:(0,o.jsxs)(e.ActionPanel,{children:[(0,o.jsx)(e.Action,{title:"Run",icon:e.Icon.Play,onAction:async()=>{await h(r.id),await g()}}),(0,o.jsx)(e.Action,{title:"Show Script File in Finder",icon:e.Icon.Finder,onAction:async()=>{await(0,e.showInFinder)(r.path),await g()}}),(0,o.jsx)(e.Action,{title:"Edit Script File",icon:e.Icon.Pencil,shortcut:{modifiers:["opt"],key:"return"},onAction:async()=>{await(0,e.open)(r.path),await g()}}),(0,o.jsx)(e.Action,{icon:e.Icon.TextCursor,title:"Run with Selected Text",shortcut:{modifiers:["cmd"],key:"e"},onAction:async()=>{let n=await(0,e.getSelectedText)();await h(r.id,n),await g()}}),(0,o.jsx)(e.Action.Push,{icon:e.Icon.Forward,shortcut:{modifiers:["cmd"],key:"l"},title:"Specify Input and Run",target:(0,o.jsx)(G,{script:r})}),(0,o.jsx)(e.Action.CopyToClipboard,{title:"Copy Deeplink",content:`okjson://script/${r.id}`,shortcut:{modifiers:["cmd"],key:"u"}})]}),icon:{source:"script-icon.png"},title:r.name,subtitle:r.description},r.id)}function C(){let[t,r]=(0,f.useState)([]),n=(0,f.useCallback)(async()=>{let a=await R();r(a)},[]);return(0,f.useEffect)(()=>{x().then(a=>{a&&n()})},[n]),(0,o.jsx)(e.List,{navigationTitle:"Run Script in OK JSON",children:t.map(a=>(0,o.jsx)(H,{script:a}))})}
